"""`uninstall`: undo everything the kit did to one project, so the workspace looks as if it had never been documented.

Project (always): stop the portal, finish an interrupted OpenWiki run, back up cam-docs/ to a .zip, remove the kit's
traces from every repo (openwiki link, its .git/info/exclude line, the CLAUDE.md pointer block, pre-3.0 leftovers),
remove the workspace-root links into cam-docs/, delete cam-docs/ and its registry entry. The repos' own files and
history are never touched: a tracked file goes back to its HEAD bytes, an untracked one the kit alone wrote is deleted.
User level (opt-in, shared by every project): ~/.camarones.json, ~/.camarones/ (registry, saved credentials, pinned
binaries — not a global kit copy in ~/.camarones/kit) and the kit's line in ~/.openwiki/.env."""
from __future__ import annotations

import datetime as dt, os, re, shutil, stat, tempfile, zipfile
from dataclasses import dataclass
from pathlib import Path

from .common import KIT, ROOT, HOME, CACHE, CAM_DIR, CAM_LAYOUT, WORKSPACE, WS_FILE, run as run_cmd, which, load_json
from . import creds, docs, env, migrate, projects

BACKUP_DIR = Path(tempfile.gettempdir()) / "camarones-backups"
BACKUP_SKIP = (".camarones/.cache/", "graph/")                    # regenerated by the kit: not worth zipping
PREFS = HOME / ".camarones.json"
USER_DIR = HOME / ".camarones"
USER_KEEP = {"kit"}                                              # the global install's kit copy (macOS/Linux)
OPENWIKI_ENV = HOME / ".openwiki" / ".env"
OPENWIKI_LINE = "OPENWIKI_TELEMETRY_DISABLED=1"
POINTER_RE = re.compile(rf"\n*{re.escape(env.POINTER_START)}.*?{re.escape(env.POINTER_END)}\n?", re.S)
Log = env.Log


@dataclass
class Step:
    kind: str       # stop | wiki | backup | repo | link | delete | registry | user
    label: str


# ---------- repos ----------
class RepoCleaner(migrate.Cleaner):
    """migrate's cleanup (pre-3.0 leftovers) plus what the cam-docs layout adds to a repo."""

    def __init__(self, name: str, dry: bool):
        super().__init__(name, dry, graph_out="delete")

    def act(self, what: str, fn=None) -> None:
        verb, _, rel = what.partition(" ")
        super().act(f"{verb} {self.name}/{rel}", fn)

    def run(self) -> list[str]:
        if not (self.repo / ".git").exists():
            return []
        ow = self.repo / "openwiki"
        if env._is_link(ow):
            self.act("unlink openwiki", lambda: remove_link(ow))
        self.lines(".git/info/exclude", ["/openwiki"])
        cm = self.repo / "CLAUDE.md"
        if cm.is_file() and env.POINTER_START in (text := cm.read_text(encoding="utf-8")) \
                and env.POINTER_START not in (migrate.head_text(self.repo, "CLAUDE.md") or ""):
            self.settle("CLAUDE.md", POINTER_RE.sub("", text))
        return super().run()


def repo_names() -> list[str]:
    """workspace.yaml's repos plus any other git repo in the workspace folder (one dropped from the list may still
    carry an openwiki link)."""
    names = list(docs.repo_names())
    names += sorted(p.name for p in WORKSPACE.iterdir() if p.is_dir() and (p / ".git").exists()
                    and p.name != CAM_DIR and p.name not in names and not p.name.startswith("."))
    return [n for n in names if (WORKSPACE / n / ".git").exists()]


def remove_link(p: Path) -> None:
    """A symlink, or a Windows junction (removed with rmdir; the target is never followed)."""
    try:
        p.unlink()
    except OSError:
        os.rmdir(p)


def root_links() -> list[str]:
    """Workspace-root entries that are links into cam-docs/ — a real file with the same name is the user's."""
    out = []
    for n in env.LINKS:
        p = WORKSPACE / n
        if env._is_link(p):
            target = Path(os.path.realpath(p))
            if target == ROOT.resolve() / n or ROOT.resolve() in target.parents:
                out.append(n)
    return out


def open_wiki_runs() -> list[str]:
    return sorted(f.stem for f in (CACHE / "wiki-open").glob("*.json"))


# ---------- user level ----------
def other_projects() -> list[dict]:
    mine = {ROOT.resolve(), WORKSPACE.resolve()}
    return [r for r in projects.list_registered() if Path(r["path"]).resolve() not in mine]


def user_steps() -> list[Step]:
    steps = []
    if PREFS.exists():
        steps.append(Step("user", "~/.camarones.json (wizard settings: language, agent, models)"))
    if USER_DIR.is_dir():
        what = sorted(p.name for p in USER_DIR.iterdir() if p.name not in USER_KEEP)
        others = other_projects()
        shared = (f" — shared with {len(others)} other project(s): {', '.join(r['name'] for r in others)}"
                  if others else "")
        if what:
            steps.append(Step("user", f"~/.camarones/ ({', '.join(what)}){shared}"))
        for host in creds.hosts():
            steps.append(Step("user", f"saved token for {host} (OS keyring)"))
    if OPENWIKI_ENV.is_file() and OPENWIKI_LINE in OPENWIKI_ENV.read_text(encoding="utf-8").splitlines():
        steps.append(Step("user", f"~/.openwiki/.env: the line {OPENWIKI_LINE} (your provider keys stay)"))
    return steps


def clean_user(log: Log) -> None:
    for host in list(creds.hosts()):
        creds.delete(host)
    PREFS.unlink(missing_ok=True)
    if USER_DIR.is_dir():
        for p in USER_DIR.iterdir():
            if p.name not in USER_KEEP:
                rmtree(p) if p.is_dir() and not env._is_link(p) else p.unlink()
        if not any(USER_DIR.iterdir()):
            USER_DIR.rmdir()
    if OPENWIKI_ENV.is_file():
        lines = OPENWIKI_ENV.read_text(encoding="utf-8").splitlines(keepends=True)
        keep = [l for l in lines if l.strip() != OPENWIKI_LINE]
        if not "".join(keep).strip():
            OPENWIKI_ENV.unlink()
            if not any(OPENWIKI_ENV.parent.iterdir()):
                OPENWIKI_ENV.parent.rmdir()
        elif keep != lines:
            OPENWIKI_ENV.write_text("".join(keep), encoding="utf-8")
    log("✔ user-level files removed")


# ---------- plan / guard ----------
def guard() -> str | None:
    """Why uninstall must not run here, or None."""
    if not WS_FILE.exists():
        return f"{ROOT} is not a Camarones project (no .camarones/workspace.yaml) — nothing to uninstall."
    if not CAM_LAYOUT:
        return (f"This project uses the pre-3.0 layout (docs next to the repos, no {CAM_DIR}/): run `migrate` first, "
                "then uninstall.")
    root, ws, home = ROOT.resolve(), WORKSPACE.resolve(), HOME.resolve()
    if root in (ws, home, Path(root.anchor)) or ws in (home, Path(ws.anchor)):
        return f"Refusing to uninstall {root}: it is your home folder or a drive root."
    kit = KIT.resolve()
    if kit == root or root in kit.parents:
        return (f"The kit running this command lives inside {CAM_DIR}/ ({kit}): run uninstall from the global "
                "install or another kit copy.")
    lock = load_json(env.WIKI_LOCK, {}) if env.WIKI_LOCK.exists() else {}
    pid = lock.get("pid") if isinstance(lock, dict) else None
    if pid and pid != os.getpid() and env.pid_alive(int(pid)):
        return f"An OpenWiki run is in progress ({lock.get('repo')}, pid {pid}): wait for it to finish, then uninstall."
    return None


def steps(include_global: bool = False, backup: bool = True) -> list[Step]:
    """What run() will do, in order — the preview (nothing is changed)."""
    out = [Step("stop", "stop the portal (local server and Docker container) if it is running")]
    out += [Step("wiki", f"finish the interrupted OpenWiki run of {r} (the repo gets its own files back)")
            for r in open_wiki_runs()]
    if backup:
        out.append(Step("backup", f"back up {CAM_DIR}/ to {BACKUP_DIR}{os.sep}{env.project_id()}-<date>.zip"))
    for name in repo_names():
        out += [Step("repo", a) for a in RepoCleaner(name, dry=True).run()]
    out += [Step("link", f"{WORKSPACE.name}/{n} → {CAM_DIR}/{n} (link)") for n in root_links()]
    out.append(Step("delete", f"{CAM_DIR}/ ({ROOT}) — docs, wikis, code graphs, agent config and its git history"))
    mine = {ROOT.resolve(), WORKSPACE.resolve()}
    if any(Path(r["path"]).resolve() in mine for r in projects.load()):
        out.append(Step("registry", f"~/.camarones/projects.json: the entry of {ROOT}"))
    if include_global:
        out += user_steps()
    return out


def untouched() -> list[str]:
    return ["the repos' own files, commits and branches (nothing was ever committed to them by this kit)",
            "tools installed globally: likec4, openwiki, mermaid-cli (npm), graphify (uv), Claude Code / Codex",
            "the kit itself: the global install and its `camarones` launcher (remove them by hand if you want)",
            "Claude Code / Codex session history (~/.claude/projects) and any branch older kits pushed for agents"]


# ---------- run ----------
def rmtree(path: Path) -> None:
    def onerror(fn, p, _exc):                    # read-only git objects on Windows
        os.chmod(p, stat.S_IWRITE)
        fn(p)
    shutil.rmtree(path, onerror=onerror)


def backup_zip(dest_dir: Path) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    zipped = dest_dir / f"{env.project_id()}-{dt.datetime.now():%Y%m%d-%H%M%S}.zip"
    with zipfile.ZipFile(zipped, "w", zipfile.ZIP_DEFLATED) as z:
        for cur, dirs, files in os.walk(ROOT, followlinks=False):
            for f in files:
                p = Path(cur) / f
                rel = p.relative_to(ROOT).as_posix()
                if not rel.startswith(BACKUP_SKIP) and not p.is_symlink():
                    z.write(p, rel)
    return zipped


def stop_services() -> None:
    env.docker_down()
    if which("docker"):
        run_cmd(["docker", "image", "rm", "-f", f"camarones-docs-{env.project_id()}:local"], check=False, quiet=True)


def run(include_global: bool = False, backup: bool = True, backup_dir: Path | None = None, log: Log = print) -> Path | None:
    """Undo the project (see the module docstring). Returns the backup .zip, if one was made."""
    why = guard()
    if why:
        raise RuntimeError(why)
    stop_services()
    log("✔ portal stopped")
    for r in open_wiki_runs():
        env.wiki_close(r, log)
    zipped = backup_zip(backup_dir or BACKUP_DIR) if backup else None
    if zipped:
        log(f"✔ backup: {zipped}")
    for name in repo_names():
        acts = RepoCleaner(name, dry=False).run()
        log(f"✔ {name}: " + (f"{len(acts)} trace(s) removed" if acts else "clean"))
    for n in root_links():
        remove_link(WORKSPACE / n)
    log(f"✔ {WORKSPACE.name}/: links into {CAM_DIR}/ removed")
    projects.unregister(ROOT, WORKSPACE)
    rmtree(ROOT)
    log(f"✔ {CAM_DIR}/ deleted")
    if include_global:
        clean_user(log)
    return zipped


def main(include_global: bool = False, dry_run: bool = False, yes: bool = False, backup: bool = True,
         backup_dir: Path | None = None) -> int:
    why = guard()
    if why:
        print(why)
        return 1
    if backup_dir:
        global BACKUP_DIR
        BACKUP_DIR = backup_dir
    name = docs.workspace()["project"]["name"]
    print(f"🧹 Uninstall {name} — remove its documentation and every trace of the kit\n")
    for s in steps(include_global, backup):
        print(f"  • {s.label}")
    print("\nNot touched:")
    for t in untouched():
        print(f"  · {t}")
    if dry_run:
        print("\n(dry run — nothing changed)")
        return 0
    if not yes:
        try:
            typed = input(f"\nType the project name ({name}) to confirm: ")
        except EOFError:
            typed = ""
        if typed.strip().casefold() != name.strip().casefold():
            print("Cancelled — nothing was removed.")
            return 1
    zipped = run(include_global, backup, backup_dir, log=print)
    print(f"\n🦐 Done: {WORKSPACE} is back to just its repos." + (f"\n   Backup of {CAM_DIR}/: {zipped}" if zipped else ""))
    return 0
